### ISSUE TITLE
无法登录（点登录之后会卡住一段时间）

### ISSUE THREAD

**Issue by hhll16384** [1328411791/GDOUYJ_Internet_Client#12]
![IMG_20230413_101749](https://user-images.githubusercontent.com/113534754/231630418-c51318a6-6a08-4842-a7b5-d31f0b75a975.jpg)

>

**Comment by 1328411791** [comment]
> ![IMG_20230413_101749](https://user-images.githubusercontent.com/113534754/231630418-c51318a6-6a08-4842-a7b5-d31f0b75a975.jpg)
> 
> > 

这个是由于执行登录界面和登录请求在同一个线程中导致的

**Comment by hhll16384** [comment]
好的，了解了，但是登录失败的问题仍然存在

**Comment by 1328411791** [comment]
这个问题已经在列队等待修复了（）
你也可以自己交pr修（）

**Comment by 1328411791** [comment]
> 好的，了解了，但是登录失败的问题仍然存在

能说不能登录是在哪个地方吗
