### ISSUE TITLE
哥们做个windows的出来看看呗

### ISSUE THREAD

**Issue by louis16s** [1328411791/GDOUYJ_Internet_Client#20]
我用python（playwright）写过一个，但是内存占用去到40m
想放到路由器上

**Comment by 1328411791** [comment]
emmm

**Comment by 1328411791** [comment]
其实你去看我使用的项目基础srun（https://github.com/zu1k/srun）用rust写的，那个其实只有500k左右，里面有基于windows/linux 的命令行实现

**Comment by louis16s** [comment]
我们GDOU，还需要加cmcc吗

Have a nice day
r祺

发件人: ***@***.***>
发送时间: 2023年6月26日 23:44
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [1328411791/GDOUYJ_Internet_Client] 哥们做个windows的出来看看呗 (Issue #20)


其实你去看我使用的项目基础srun（https://github.com/zu1k/srun）用rust写的，那个其实只有500k左右<https://github.com/zu1k/srun%EF%BC%89%E7%94%A8rust%E5%86%99%E7%9A%84%EF%BC%8C%E9%82%A3%E4%B8%AA%E5%85%B6%E5%AE%9E%E5%8F%AA%E6%9C%89500k%E5%B7%A6%E5%8F%B3>

―

**Comment by 1328411791** [comment]
我这边测试的是不用的

**Comment by louis16s** [comment]
Okok 明天下课试一下

Have a nice day
r祺

发件人: ***@***.***>
发送时间: 2023年6月26日 23:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [1328411791/GDOUYJ_Internet_Client] 哥们做个windows的出来看看呗 (Issue #20)


我这边测试的是不用的

―

**Comment by 1328411791** [comment]
应该是不用的，config可以参考这个https://github.com/1328411791/GDOUYJ_Internet_Client/blob/master/app/lib/arm64-v8a/config.json

**Comment by BenChuat** [comment]
学长，能不能带带学弟我

**Comment by 1328411791** [comment]
> 学长，能不能带带学弟我

？？？
